config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  devise_for :end_users
	resources :places do
		resources :comments
	end
	resources :songs do
		resources :comments
	end
	resources :poems do
		resources :comments
	end
	resources :composers
	resources :end_users

	get '/index', to: 'poems#index'
	get '/index', to: 'songs#index'
	get '/index', to: 'places#index'
	get '/index', to: 'composers#index'
	get '/index', to: 'end_users#index'
	
	get '/home', to: 'application#home'
	get '/about', to: 'application#about'
	get '/contact', to: 'application#contact'
	get '/signup', to: 'application#signup'

	root to: 'application#home'
end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :commentable, polymorphic: true
  belongs_to :end_user
end

app/models/composer.rb
class Composer < ActiveRecord::Base

	belongs_to :end_user
	
	has_many :songs
	has_many :poems
	has_many :places, through: :songs
	has_many :places, through: :poems

	validates :fname, presence: true
	validates :lname, presence: true
end

app/models/end_user.rb
class EndUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable       
  has_many :songs
  has_many :poems
  has_many :places
  has_many :composers
  has_many :comments
end

app/models/place.rb
class Place < ActiveRecord::Base
	
	belongs_to :end_user

	has_many :poems
	has_many :songs
	has_many :composers, through: :songs
	has_many :composers, through: :poems
	has_many :comments, as: :commentable

	validates :latitude, presence: true
	validates :longitude, presence: true 
end

app/models/poem.rb
class Poem < ActiveRecord::Base
	
	belongs_to :end_user
	belongs_to :place
	belongs_to :composer
	has_many :comments, as: :commentable

	has_attached_file :medialink,
	:storage => :s3,
	:url => ":s3_domain_url",
	:path => "poems/:id/:filename",
	:s3_credentials => {
		:bucket => ENV['S3_BUCKET_NAME'],
		:access_key_id => ENV['AWS_ACCESS_KEY_ID'],
		:secret_access_key => ENV['AWS_SECRET_ACCESS_KEY']
	}

	validates_attachment_content_type :medialink, :content_type => /.*/
	
	validates :title, presence: true
	validates :subtitle, presence: true

end

app/models/song.rb
class Song < ActiveRecord::Base

	belongs_to :end_user
	belongs_to :place
	belongs_to :composer
	has_many :comments, as: :commentable

	has_attached_file :medialink,
	:storage => :s3,
	:url => ":s3_domain_url",
	:path => "songs/:id/:filename",
	:s3_credentials => {
		:bucket => ENV['S3_BUCKET_NAME'],
		:access_key_id => ENV['AWS_ACCESS_KEY_ID'],
		:secret_access_key => ENV['AWS_SECRET_ACCESS_KEY']
	}

	validates_attachment_content_type :medialink, :content_type => /.*/

	validates :title, presence: true
	validates :lyrics, presence: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception


  def authenticate_end_user!
    return if admin_signed_in?
    super
  end

  def songs
  end

  def poems
  end

  def composers
  end

  def places
  end

  def home
  end

  def signup
  end

  def contact
  end

  def about
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	before_action :authenticate_end_user!

	def create
		@comment = Comment.create(params[:comment].permit(:content))
		@comment.end_user_id = current_end_user.id

		if @comment.save
			redirect_to :back
		end
	end
end

app/controllers/composers_controller.rb
class ComposersController < ApplicationController
	before_action :find_composer, only: [:show, :edit, :update, :destroy]
	before_action :authenticate_end_user!, except: [:index, :show]

	def index
		@composers = Composer.all.order("created_at DESC")
	end

	def show
	end

	def new
		@composer = current_end_user.composers.build
	end

	def create
		@composer = current_end_user.composers.build(composer_params)

		if @composer.save
			redirect_to @composer
		else
			render 'new'
		end
	end

	def edit
	end

	def update
		if @composer.update(composer_params)
			redirect_to @composer
		else
			render 'edit'
		end
	end

	def destroy
		@composer.destroy
		redirect_to composers_path
	end

	private

	def find_composer
		@composer = Composer.find(params[:id])
	end

	def composer_params
		params.require(:composer).permit(:fname, :lname, :category, :bio)
	end
end

app/controllers/end_users_controller.rb
class EndUsersController < ApplicationController
before_action :authenticate_admin!

  def index
	 @end_users = EndUser.all    
  end
	
	def show
	  @end_user = EndUser.find(params[:id])
	end 
  
  def destroy
    EndUser.find(params[:id]).destroy
    redirect_to end_users_path
  end
  	
  private

  def end_user_params
    params.require(:end_user).permit(:email, :password,
                                 :password_confirmation)
  end
end

app/controllers/places_controller.rb
class PlacesController < ApplicationController
	before_action :find_place, only: [:show, :edit, :update, :destroy]
	before_action :authenticate_end_user!, except: [:index, :show]

	def index
		@places = Place.all.order("created_at DESC")
	end

	def show
		@place = Place.find(params[:id])
		@songs = @place.songs
		@poems = @place.poems
		@comments = Comment.where(commentable_id: @commentable)
	end

	def new
		@place = current_end_user.places.build
	end

	def create
		@place = current_end_user.places.build(place_params)

		if @place.save
			redirect_to new_composer_path
		else
			render 'new'
		end
	end

	def edit
	end

	def update
		if @place.update(place_params)
			redirect_to @place
		else
			render 'edit'
		end
	end

	def destroy
		@place.destroy
		redirect_to root_path
	end

	private

	def find_place
		@place = Place.find(params[:id])
	end

	def place_params
		params.require(:place).permit(:name, :latitude, :longitude, :region, :image)
	end
end

app/controllers/poems_controller.rb
class PoemsController < ApplicationController
	before_action :authenticate_end_user!, except: [:index, :show]
	before_action :find_poem, only: [:show, :edit, :update, :destroy]
	
	def index
		@poems = Poem.all.order("created_at DESC")
	end

	def show
		@poem = Poem.find(params[:id])
		@place = @poem.place
	end

	def new
		@poem = current_end_user.poems.build
	end

	def create
		@poem = current_end_user.poems.build(poem_params)

		if @poem.save
			redirect_to @poem
		else
			render 'new'
		end
	end

	def edit
	end

	def update
		if @poem.update(poem_params)
			redirect_to @poem
		else
			render 'edit'
		end
	end

	def destroy
		@poem.destroy
		redirect_to root_path
	end

	private

	def find_poem
		@poem = Poem.find(params[:id])
	end

	def poem_params
		params.require(:poem).permit(:title, :description, :medialink, :subtitle, :place_id, :composer_id)
	end
end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
	before_action :authenticate_end_user!, except: [:index, :show]
	before_action :find_song, only: [:show, :edit, :update, :destroy]
	
	
	def index
		@songs = Song.all.order("created_at DESC")
	end

	def show
		@song = Song.find(params[:id])
		@place = @song.place
	end

	def new
		@song = current_end_user.songs.build
	end

	def create
		@song = current_end_user.songs.build(song_params)

		if @song.save
			redirect_to @song
		else
			render 'new'
		end
	end

	def edit
	end

	def update
		if @song.update(song_params)
			redirect_to @song
		else
			render 'edit'
		end
	end

	def destroy
		@song.destroy
		redirect_to root_path
	end

	private

	def find_song
		@song = Song.find(params[:id])
	end

	def song_params
		params.require(:song).permit(:title, :description, :medialink, :lyrics, :place_id, :composer_id)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper 
	def name(x)
		@name = Place.find(x).name
		return @name
	end

	def latitude(x)
		@latitude = Place.find(x).latitude
		return @latitude
	end

	def longitude(x)
		@longitude = Place.find(x).longitude
		return @longitude
	end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/composers_helper.rb
module ComposersHelper
end

app/helpers/end_users_helper.rb
module EndUsersHelper
end

app/helpers/places_helper.rb
module PlacesHelper
end

app/helpers/poems_helper.rb
module PoemsHelper
end

app/helpers/songs_helper.rb
module SongsHelper
end

app/views/application/about.html.erb
<h2> About the application </h2>

<p>This project aims to develop a dynamic application intended to be used by culture and tradition enthusiast as well as those wanting to find out more about local history. </p> <br\>
<p> It features functions such as geolocation; a database with a number of ballads; social network links allowing the user to share ballads they like; and many others. </p> <br\>
<p> If used outdoors, the geolocation function will show a concrete position of the user who will subsequently be able to see ballads that had been written in the area. </p>

app/views/application/contact.html.erb
<form class="form-horizontal" role="form" method="post" name="form" onsubmit="return validateForm()">
    <div class="form-group">
        <label form="name" name="name" class="col-sm-2 control-label">Name</label>
        <div class="col-sm-10">
            <input type="text" class="form-control" id="name" name="name" placeholder="First & Last Name" value="">
        </div>
    </div>
    <div class="form-group">
        <label form="email" name="email" class="col-sm-2 control-label">Email</label>
        <div class="col-sm-10">
            <input type="email" class="form-control" id="email" name="email" placeholder="example@domain.com" value="">
        </div>
    </div>
    <div class="form-group">
        <label form="message" class="col-sm-2 control-label">Message</label>
        <div class="col-sm-10">
            <textarea class="form-control" rows="4" name="textarea"></textarea>
        </div>
    </div>
        <div class="col-sm-10 col-sm-offset-2">
            <input id="submit" name="submit" type="submit" value="Send" class="btn btn-primary">
        </div>
    </div>
    <div class="form-group">
        <div class="col-sm-10 col-sm-offset-2">
            <! Will be used to display an alert to the user>
        </div>
    </div>
</form>

<script>
	function validateForm() {
    var x = document.forms["form"]["name"].value;
    if (x == null || x == "") {
        alert("Name must be filled out");
        return false;
    }

    var y = document.forms["form"]["email"].value;
    if (y == null || y == "") {
        alert("Email must be filled out");
        return false;
    }
    
    var email = document.forms["form"]["email"].value;
    var regex = /^([0-9a-zA-Z]([-_\\.]*[0-9a-zA-Z]+)*)@([0-9a-zA-Z]([-_\\.]*[0-9a-zA-Z]+)*)[\\.]([a-zA-Z]{2,9})$/;

    if(!regex.test(email)){
        alert("Please enter a valid email");
        return false;
    }

    var z = document.forms["form"]["textarea"].value;
    if (z == null || z == "") {
        alert("Message must be filled out");
        return false;
    }

}
</script>

app/views/application/home.html.erb
<div class="container-fluid">
	<div class="jumbotron">
  	<h2 align="center">WELCOME TO <br>THE BALLAD TRAIL</h2>
	</div>
	<p> To find out more about the application, select 'About' from the menu. </p>
	<p> To browse our ballad database, use the search option.</p>
	<p> To add your ballads, login (or signup) first and then click 'new ballad'.</p>
</div>

app/views/application/signup.html.erb
<h1>Sign up</h1>

app/views/comments/_form.html.erb
<%= form_for Comment.new do |f| %>
	<% if @song.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this song from being saved:</h2>

      <ul>
      <% @comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
  	<%= f.text_area :content, rows: 8 %>
  </div>
  <div class="actions">
  	<%= f.submit %>
  </div>
  <% end %>

app/views/composers/_form.html.erb
<%= simple_form_for @composer do |f| %>
	<%= f.input :fname, label: 'First name'%>
	<%= f.input :lname, label: 'Last name'%>
	<%= f.input :category, hint: 'Singer or Poet' %>
	<%= f.input :bio, hint: 'Brief Composer bio. You can also include links to external sources'%>
	<%= f.button :submit %>
<% end %>

app/views/composers/edit.html.erb
<h3>Edit Composer</h3>

<%= render 'form' %>

app/views/composers/index.html.erb
<h1>Composers Page</h1>

<% @composers.each do |composer| %>
	<h3><%= link_to composer.fname, composer %></h3>
	<% end %>
	

app/views/composers/new.html.erb
<h1>Add New Composer</h1>
<h2>Step 2</h2>
<p>Tell us more about the composer of the Ballad.</p>

<%= render 'form' %>

<%= link_to 'Next', composers_path %>

app/views/composers/show.html.erb
<h3><%= @composer.fname %> <%= @composer.lname %></h3>
<p><%= @composer.category %></p>
<p><%= @composer.bio %></p>

<p><% if @composer.end_user == current_end_user %></p>
	<p><strong><%= link_to 'Edit', edit_composer_path %></strong></p>

	<p><strong><%= link_to "Destroy", composer_path(@composer), method: :delete, data: { confirm: "Are you sure?"} %></strong></p>
<% elsif end_user_signed_in? %>
	<p><%= link_to 'Add new ballad', new_place_path %></p>
<% else %>
<p><strong><%= link_to 'Sign in to add new ballads', new_end_user_session_path %></strong></p>
<% end %>

<% if admin_signed_in? %>
<p><strong><%= link_to 'Edit', edit_composer_path %></strong></p>
<p><strong><%= link_to "Destroy", composer_path(@composer), method: :delete, data: { confirm: "Are you sure?"} %></strong></p>
<% end %>

	

app/views/end_users/_end_user.html.erb
<li>
  <%= link_to end_user.email , end_user %>
<%= link_to "delete", end_user, method: :delete,
                                  data: { confirm: "Are you sure?" } %>
</li>

app/views/end_users/index.html.erb
<% provide(:title, 'All users') %>

<h1>All users</h1>

<ul class="end_users">
  <%= render @end_users %>
</ul>

app/views/end_users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/end_users/show.html.erb
<% provide(:title, @end_user.email) %>

<%= @end_user.email %>
   

app/views/places/_form.html.erb
<%= simple_form_for @place do |f| %>
	<%= f.input :name, hint: 'e.g. Harlaw' %>
	<%= f.input :latitude, hint: 'Use google maps to find the latitude of the place e.g. "57.291939"' %>
	<%= f.input :longitude, hint: 'Use google maps to find the longitude of the place e.g. "-2.565474"'%>
	<%= f.input :region, hint: 'e.g. Inverurie' %>
	<%= f.input :image, hint: 'Insert image link directly from source' %>
	<%= f.button :submit %>
<% end %>

app/views/places/edit.html.erb
<h3>Edit Place</h3>

<%= render 'form' %>

app/views/places/index.html.erb
<h1>PLACES </h1>

<div class="table-responsive">
	<table class="table table-condensed">
		<tbody>
			<% @places.each do |place| %>
				<tr><div class="col-md-12">
					<td><div class="thumbnail">
					<%= image_tag place.image %>
					</div></td>
					<td><div class="placename">
					<h4><%= link_to place.name, place %></h4>
					</div></td>
				</div></tr>
			<% end %>
		</tbody>
	</table>
</div>



<% if end_user_signed_in? %>
	<p><%= link_to 'Fancy adding a Ballad?', new_place_path %></p>
<% else %>
	<p><%= link_to 'Sign in to add new ballads', new_end_user_session_path %></p>
<% end %>

app/views/places/new.html.erb
<h1>Add New Place</h1>
<h2>Step 1</h2>
<p>Tell us more about the place your Ballad is about.</p>

<%= render 'form' %>

<!-- Insert link to return/go back -->

app/views/places/show.html.erb
<div class="container-fluid">
	<h4><%= @place.name %></h4>
	<div class="imgshow">
		<%= image_tag @place.image, :class => "showimg" %>
	</div>
	<div class="table-responsive">
		<table class="table">
			<tbody>
				<tr>
					<td><strong>Region</strong></td>
					<td><%= @place.region %></td>
				</tr>
			</tbody>
		</table>
		<h4>Songs about <%= @place.name %></h4>
		<p><%= render @songs %></p>
		<br>
		<h4>Poems about <%= @place.name %></h4>
		<p><%= render @poems %></p>
	</div>

<br>

	<div>
		<h2>Comments</h2>
		<% @comments.each do |comment| %>
		<div class="comment">
			<p>UserEmail<%= comment.user.email %></p>
			<p>Content<%= comment.content %></p> 
		</div>
		<% end %>	
	</div>

	<p><% if @place.end_user == current_end_user %></p>
	<p><strong><%= link_to 'Edit', edit_place_path %></strong></p>

	<p><strong><%= link_to "Destroy", place_path(@place), method: :delete, data: { confirm: "Are you sure?"} %></strong></p>
<% elsif end_user_signed_in? %>
<p><%= link_to 'Add new ballad', new_place_path %></p>
<% else %>
<p><strong><%= link_to 'Sign in to add new ballads', new_end_user_session_path %></strong></p>
<% end %>

<% if admin_signed_in? %>
<p><strong><%= link_to 'Edit', edit_place_path %></strong></p>
<p><strong><%= link_to "Destroy", place_path(@place), method: :delete, data: { confirm: "Are you sure?"} %></strong></p>
<% end %>
</div>

app/views/poems/_form.html.erb
<%= form_for @poem, html: { multipart: true } do |f| %>
  <% if @poem.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@poem.errors.count, "error") %> prohibited this song from being saved:</h2>

      <ul>
      <% @poem.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :medialink %><br>
    <%= f.file_field :medialink %>
  </div>
  <div class="field">
    <%= f.label :subtitle %><br>
    <%= f.text_area :subtitle %>
  </div>
  <div>
  	<%= f.label :composer_id %>
    <%= f.collection_select :composer_id, Composer.all, :id, :fname %>
  </div>
  <div>
  	<%= f.label :place_id %>
    <%= f.collection_select :place_id, Place.all, :id, :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/poems/_poem.html.erb
<h5><%= link_to poem.title, poem %></h5>

app/views/poems/edit.html.erb
<h3>Edit Poem</h3>

<%= render 'form' %>

app/views/poems/index.html.erb
<div class="page-header">
	<h1>POEMS</h1>
</div>

<p><% @poems.each do |poem| %></p>
	<h3><%= link_to poem.title, poem %></h3>
	<h5>Created by: <%= poem.end_user.email %></h5>
<% end %>
<br>

</br>
<% if end_user_signed_in? %>
<p><%= link_to 'Fancy adding a Ballad?', new_place_path %></p>
<% else %>
<p><%= link_to 'Sign in to add new ballads', new_end_user_session_path %></p>
<% end %>

app/views/poems/new.html.erb
<h1>Add New Poem</h1>
<h2>Step 3</h2>
<p>Upload your poem here.</p>

<%= render 'form' %>

<%= link_to 'Next', poems_path %>

app/views/poems/show.html.erb
<div class="container-fluid">
	<h3><%= @poem.title %></h3>
	<br>
	<div>
		<img src="<%= @poem.place.image %>" class="img-circle" width="60" height="50">

		<audio controls>
			<source src="<%= @poem.medialink %>" type="audio/mpeg">
				Your browser does not support the audio element.
		</audio>
		<h4>About the ballad:</h4>
		<p><%= @poem.description %></p>
		<h4>Lyrics:</h4>
		
		<button type="button" class=".btn-success" data-toggle="collapse" data-target="#demo">Click to view</button>
		<div id="demo" class="collapse"><p><%= @poem.subtitle %></p></div>
	</div>
	<p><% if @poem.end_user == current_end_user %></p>
	<p><strong><%= link_to 'Edit', edit_poem_path %></strong></p>

	<p><strong><%= link_to "Destroy", poem_path(@poem), method: :delete, data: { confirm: "Are you sure?"} %></strong></p>
<% elsif end_user_signed_in? %>
<p><%= link_to 'Add new ballad', new_poem_path %></p>
<% else %>
<p><strong><%= link_to 'Sign in to add new ballads', new_end_user_session_path %></strong></p>
<% end %>

<% if admin_signed_in? %>
<p><strong><%= link_to 'Edit', edit_poem_path %></strong></p>
<p><strong><%= link_to "Destroy", poem_path(@place), method: :delete, data: { confirm: "Are you sure?"} %></strong></p>
<% end %>

	
</div>

app/views/songs/_form.html.erb
<%= form_for @song, html: { multipart: true } do |f| %>
  <% if @song.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@song.errors.count, "error") %> prohibited this song from being saved:</h2>

      <ul>
      <% @song.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :medialink %><br>
    <%= f.file_field :medialink %>
  </div>
  <div class="field">
    <%= f.label :lyrics %><br>
    <%= f.text_area :lyrics %>
  </div>
  <div>
  	<%= f.label :composer_id %>
    <%= f.collection_select :composer_id, Composer.all, :id, :fname %>
  </div>
  <div>
  	<%= f.label :place_id %>
    <%= f.collection_select :place_id, Place.all, :id, :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/songs/_song.html.erb
<h5><%= link_to song.title, song %></h5>

app/views/songs/edit.html.erb
<h3>Edit Song</h3>

<%= render 'form' %>

app/views/songs/index.html.erb
<div class="page-header">
	<h1>SONGS</h1>
</div>

<p><% @songs.each do |song| %></p>
	<h3><%= link_to song.title, song %></h3>
	<h5>Created by: <%= song.end_user.email %></h5>
<% end %>
<br>

</br>
<% if end_user_signed_in? %>
<p><%= link_to 'Fancy adding a Ballad?', new_place_path %></p>
<% else %>
<p><%= link_to 'Sign in to add new ballads', new_end_user_session_path %></p>
<% end %>

app/views/songs/new.html.erb
<h1>Add New Song</h1>
<h2>Step 3</h2>
<p>Check if the Composer of the song exists. if not, <strong><%= link_to 'add new Composer', new_composer_path %></strong></p>
<%= render 'form' %>

<!-- <%= link_to 'Next', songs_path %> -->

app/views/songs/show.html.erb
<div class="container-fluid">
	<h3><%= @song.title %></h3>
	<br>
	<div>
		<img src="<%= @song.place.image %>" class="img-circle" width="60" height="50">

		<audio controls>
			<source src="<%= @song.medialink %>" type="audio/mpeg">
				Your browser does not support the audio element.
		</audio>
		<h4>About the ballad:</h4>
		<p><%= @song.description %></p>
		<h4>Lyrics:</h4>
		
		<button type="button" class=".btn-success" data-toggle="collapse" data-target="#demo">Click to view</button>
		<div id="demo" class="collapse"><p><%= @song.lyrics %></p></div>
	</div>
	<p><% if @song.end_user == current_end_user %></p>
		<p><strong><%= link_to 'Edit', edit_song_path %></strong></p>

	<p><strong><%= link_to "Destroy", song_path(@place), method: :delete, data: { confirm: "Are you sure?"} %></strong></p>
<% elsif end_user_signed_in? %>
<p><%= link_to 'Add new ballad', new_song_path %></p>
	<% else %>
			<p><strong><%= link_to 'Sign in to add new ballads', new_end_user_session_path %></strong></p>
	<% end %>

<% if admin_signed_in? %>
<p><strong><%= link_to 'Edit', edit_song_path %></strong></p>
<p><strong><%= link_to "Destroy", song_path(@song), method: :delete, data: { confirm: "Are you sure?"} %></strong></p>
<% end %>

	
</div>