config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  devise_for :end_users
	resources :places do
		resources :comments
	end
	resources :songs do
		resources :comments
	end
	resources :poems do
		resources :comments
	end
	resources :composers
	resources :end_users

	get '/index', to: 'poems#index'
	get '/index', to: 'songs#index'
	get '/index', to: 'places#index'
	get '/index', to: 'composers#index'
	get '/index', to: 'end_users#index'
	
	get '/home', to: 'application#home'
	get '/about', to: 'application#about'
	get '/contact', to: 'application#contact'
	get '/signup', to: 'application#signup'

	root to: 'application#home'
end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :commentable, polymorphic: true
  belongs_to :end_user
end

app/models/composer.rb
class Composer < ActiveRecord::Base

	belongs_to :end_user
	
	has_many :songs
	has_many :poems
	has_many :places, through: :songs
	has_many :places, through: :poems

	validates :fname, presence: true
	validates :lname, presence: true
end

app/models/end_user.rb
class EndUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable       
  has_many :songs
  has_many :poems
  has_many :places
  has_many :composers
  has_many :comments
end

app/models/place.rb
class Place < ActiveRecord::Base
	
	belongs_to :end_user

	has_many :poems
	has_many :songs
	has_many :composers, through: :songs
	has_many :composers, through: :poems
	has_many :comments, as: :commentable

	validates :latitude, presence: true
	validates :longitude, presence: true 
end

app/models/poem.rb
class Poem < ActiveRecord::Base
	
	belongs_to :end_user
	belongs_to :place
	belongs_to :composer
	has_many :comments, as: :commentable

	has_attached_file :medialink,
	:storage => :s3,
	:url => ":s3_domain_url",
	:path => "poems/:id/:filename",
	:s3_credentials => {
		:bucket => ENV['S3_BUCKET_NAME'],
		:access_key_id => ENV['AWS_ACCESS_KEY_ID'],
		:secret_access_key => ENV['AWS_SECRET_ACCESS_KEY']
	}

	validates_attachment_content_type :medialink, :content_type => /.*/
	
	validates :title, presence: true
	validates :subtitle, presence: true

end

app/models/song.rb
class Song < ActiveRecord::Base

	belongs_to :end_user
	belongs_to :place
	belongs_to :composer
	has_many :comments, as: :commentable

	has_attached_file :medialink,
	:storage => :s3,
	:url => ":s3_domain_url",
	:path => "songs/:id/:filename",
	:s3_credentials => {
		:bucket => ENV['S3_BUCKET_NAME'],
		:access_key_id => ENV['AWS_ACCESS_KEY_ID'],
		:secret_access_key => ENV['AWS_SECRET_ACCESS_KEY']
	}

	validates_attachment_content_type :medialink, :content_type => /.*/

	validates :title, presence: true
	validates :lyrics, presence: true

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	before_action :authenticate_end_user!

	def create
		@comment = Comment.create(params[:comment].permit(:content))
		@comment.end_user_id = current_end_user.id

		if @comment.save
			redirect_to :back
		end
	end
end

app/controllers/composers_controller.rb
class ComposersController < ApplicationController
	before_action :find_composer, only: [:show, :edit, :update, :destroy]
	before_action :authenticate_end_user!, except: [:index, :show]

	def index
		@composers = Composer.all.order("created_at DESC")
	end

	def show
	end

	def new
		@composer = current_end_user.composers.build
	end

	def create
		@composer = current_end_user.composers.build(composer_params)

		if @composer.save
			redirect_to @composer
		else
			render 'new'
		end
	end

	def edit
	end

	def update
		if @composer.update(composer_params)
			redirect_to @composer
		else
			render 'edit'
		end
	end

	def destroy
		@composer.destroy
		redirect_to composers_path
	end

	private

	def find_composer
		@composer = Composer.find(params[:id])
	end

	def composer_params
		params.require(:composer).permit(:fname, :lname, :category, :bio)
	end
end

app/controllers/end_users_controller.rb
class EndUsersController < ApplicationController
before_action :authenticate_admin!

  def index
	 @end_users = EndUser.all    
  end
	
	def show
	  @end_user = EndUser.find(params[:id])
	end 
  
  def destroy
    EndUser.find(params[:id]).destroy
    redirect_to end_users_path
  end
  	
  private

  def end_user_params
    params.require(:end_user).permit(:email, :password,
                                 :password_confirmation)
  end
end

app/controllers/places_controller.rb
class PlacesController < ApplicationController
	before_action :find_place, only: [:show, :edit, :update, :destroy]
	before_action :authenticate_end_user!, except: [:index, :show]

	def index
		@places = Place.all.order("created_at DESC")
	end

	def show
		@place = Place.find(params[:id])
		@songs = @place.songs
		@poems = @place.poems
		@comments = Comment.where(commentable_id: @commentable)
	end

	def new
		@place = current_end_user.places.build
	end

	def create
		@place = current_end_user.places.build(place_params)

		if @place.save
			redirect_to new_composer_path
		else
			render 'new'
		end
	end

	def edit
	end

	def update
		if @place.update(place_params)
			redirect_to @place
		else
			render 'edit'
		end
	end

	def destroy
		@place.destroy
		redirect_to root_path
	end

	private

	def find_place
		@place = Place.find(params[:id])
	end

	def place_params
		params.require(:place).permit(:name, :latitude, :longitude, :region, :image)
	end
end

app/controllers/poems_controller.rb
class PoemsController < ApplicationController
	before_action :authenticate_end_user!, except: [:index, :show]
	before_action :find_poem, only: [:show, :edit, :update, :destroy]
	
	def index
		@poems = Poem.all.order("created_at DESC")
	end

	def show
		@poem = Poem.find(params[:id])
		@place = @poem.place
	end

	def new
		@poem = current_end_user.poems.build
	end

	def create
		@poem = current_end_user.poems.build(poem_params)

		if @poem.save
			redirect_to @poem
		else
			render 'new'
		end
	end

	def edit
	end

	def update
		if @poem.update(poem_params)
			redirect_to @poem
		else
			render 'edit'
		end
	end

	def destroy
		@poem.destroy
		redirect_to root_path
	end

	private

	def find_poem
		@poem = Poem.find(params[:id])
	end

	def poem_params
		params.require(:poem).permit(:title, :description, :medialink, :subtitle, :place_id, :composer_id)
	end
end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
	before_action :authenticate_end_user!, except: [:index, :show]
	before_action :find_song, only: [:show, :edit, :update, :destroy]
	
	
	def index
		@songs = Song.all.order("created_at DESC")
	end

	def show
		@song = Song.find(params[:id])
		@place = @song.place
	end

	def new
		@song = current_end_user.songs.build
	end

	def create
		@song = current_end_user.songs.build(song_params)

		if @song.save
			redirect_to @song
		else
			render 'new'
		end
	end

	def edit
	end

	def update
		if @song.update(song_params)
			redirect_to @song
		else
			render 'edit'
		end
	end

	def destroy
		@song.destroy
		redirect_to root_path
	end

	private

	def find_song
		@song = Song.find(params[:id])
	end

	def song_params
		params.require(:song).permit(:title, :description, :medialink, :lyrics, :place_id, :composer_id)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper 
	def name(x)
		@name = Place.find(x).name
		return @name
	end

	def latitude(x)
		@latitude = Place.find(x).latitude
		return @latitude
	end

	def longitude(x)
		@longitude = Place.find(x).longitude
		return @longitude
	end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/composers_helper.rb
module ComposersHelper
end

app/helpers/end_users_helper.rb
module EndUsersHelper
end

app/helpers/places_helper.rb
module PlacesHelper
end

app/helpers/poems_helper.rb
module PoemsHelper
end

app/helpers/songs_helper.rb
module SongsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
		<meta charset="utf-8">
			<title>TheBalladTrail</title>
			<%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
			<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
			<%= csrf_meta_tags %>
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<link href="assets/css/bootstrap-responsive.css" rel="stylesheet">
		
		<!-- Add styles to map -->
		<style type="text/css">
			html, body, #map-canvas { position: relative; width: 100%; height: 100%; margin: 0; padding: 0;}
		</style>
		
		<!-- Connects to Google Javascript API -->
		<script type="text/javascript"
			src="https://maps.googleapis.com/maps/api/js?key=AIzaSyAz0j_R1FllX2cnZ_lJIsgZJtMitbI6vOY">
		</script>
		
		<!-- Initializes map and creates map object and markers -->
		<script type="text/javascript">
			function initialize() {
			
				// Sets up coordinates (latitude, longitude) for markers
				var myLatlng1 = new google.maps.LatLng(<%= latitude(1) %>, <%= longitude(1)%>)
				var myLatlng2 = new google.maps.LatLng(<%= latitude(2) %>, <%= longitude(2) %>)
				var myLatlng3 = new google.maps.LatLng(<%= latitude(3) %>, <%= longitude(3) %>)
				var myLatlng4 = new google.maps.LatLng(<%= latitude(4) %>, <%= longitude(4) %>)
				
				// Centers marker over Aberdeen and sets zoom level to 10
				var mapOptions = {
					center: { lat: 57.331380, lng: -2.320982},
					zoom: 10
				};
				
				// Sets up map
				var map = new google.maps.Map(document.getElementById('map-canvas'),
				mapOptions);
				
				// Markers to be displayed
				// Markers contain coordinates set in myLatlng variables, and make a method call to application_helper to display a name from the model Place
				var marker1 = new google.maps.Marker({
					position: myLatlng1,
					map: map,
					title: "<%= name(1) %>"
				});
				
				var marker2 = new google.maps.Marker({
					position: myLatlng2,
					map: map,
					title: "<%= name(2) %>"
				});
				
				var marker3 = new google.maps.Marker({
					position: myLatlng3,
					map: map,
					title: "<%= name(3) %>"
				});
				
				var marker4 = new google.maps.Marker({
					position: myLatlng4,
					map: map,
					title: "<%= name(4) %>"
				});
			}
			
			google.maps.event.addDomListener(window, 'load', initialize);
		</script>
	</head>
	<body>
		<script type='text/javascript'>
			(function()
				{
					if( window.localStorage )
				{
					if( !localStorage.getItem( 'firstLoad' ) )
				{
					localStorage[ 'firstLoad' ] = true;
					window.location=window.location;
				}
					else
					localStorage.removeItem( 'firstLoad' );
				}
			})();
		</script>
		
		<div class="header">
			<%= link_to image_tag("logo.png", :style => 'margin-top: 15px;'), home_path %>
		<div class="userName">
			<% if end_user_signed_in? %>
				Logged in as <strong><%= current_end_user.email %></strong>
			<% end %>
			
			<% if admin_signed_in? %>
				Logged in as <strong>Administrator</strong>
			<% end %>
		</div>

		<!-- Links to like on social media -->
		<div class="share-buttons">
			<li><%= link_to image_tag("facebook.png", :style => ''), "http://www.facebook.com/" %></li>
			<li><%= link_to image_tag("twitter.png", :style => ''), "https://twitter.com" %> </li>
		</div>
		
		</div>
			<nav class="navbar navbar-default" style="margin-bottom: 0px;">

				<div class="container-fluid">
					<div class="navbar-header">
						<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
							<span class="sr-only">Toggle navigation</span>
							<span class="icon-bar"></span>
							<span class="icon-bar"></span>
							<span class="icon-bar"></span>
						</button>
				
						<button class="navbar-brand"><%= image_tag("list.png", :style => 'margin-top: -5px;') %></button>
					</div>
					<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
						<ul class="nav navbar-nav">
							<li class="dropdown">
								<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Ballads <span class="caret"></span></a>
								<ul class="dropdown-menu">
									<li><%= link_to 'Poems', poems_path %> </li>
									<li><%= link_to 'Songs', songs_path %> </li>
									<li><%= link_to 'Add new Ballad', new_place_path %></li>
								</ul>
							</li>

							<li><%= link_to 'Places', places_path %> </li>	
							<li><% if admin_signed_in? %>
										<%= link_to 'All Users', end_users_path %>
									<% end %> 
							</li>
						</ul>

						<ul class="nav navbar-nav navbar-right">
							<li class="dropdown">
							<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><strong>Menu </strong><span class="caret"></span></a>
							<ul class="dropdown-menu">
								<% if end_user_signed_in? %>
									<li><%= link_to image_tag("home.png", :style => 'margin-right: 100px;') + 'Home', home_path %></li>
									<li><%= link_to image_tag("about.png", :style => 'margin-right: 100px;') + 'About', about_path %></li>
									<li><%= link_to image_tag("contact.png", :style => 'margin-right: 100px;') + 'Contact us', contact_path %></li>
								<% elsif admin_signed_in? %>
									<li><%= link_to image_tag("home.png", :style => 'margin-right: 100px;') + 'Home', home_path %></li>
								<% else %>
									<li><%= link_to image_tag("home.png", :style => 'margin-right: 100px;') + 'Home', home_path %></li>
									<li><%= link_to image_tag("about.png", :style => 'margin-right: 100px;') + 'About', about_path %></li>
									<li><%= link_to image_tag("contact.png", :style => 'margin-right: 100px;') + 'Contact us', contact_path %></li>
									<li><%= link_to image_tag("admin.png", :style => 'margin-right: 100px;') + 'Admin Controls', new_admin_session_path %></li>
								<% end %>
							</ul>
							<% if end_user_signed_in? %>
								<li><%= link_to 'Logout', destroy_end_user_session_path, method: :delete %></li>
							<% elsif admin_signed_in? %>
								<li><%= link_to "Logout", destroy_admin_session_path, method: :delete %></li>
							<% else %>
								<li><%= link_to 'Signup', new_end_user_registration_path %></li>
								<li><%= link_to "Login", new_end_user_session_path %></li>
								<% end %>

			  <div class="container-fluid">
			    <div class="navbar-header">
			      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
			        <span class="sr-only">Toggle navigation</span>
			        <span class="icon-bar"></span>
			        <span class="icon-bar"></span>
			        <span class="icon-bar"></span>
			      </button>
			      <button class="navbar-brand"><%= image_tag("list.png", :style => 'margin-top: -5px;') %></button>
		    	</div>

		    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
		      <ul class="nav navbar-nav">
		        <li><%= link_to 'Home', home_path %> </li>
		        <li class="dropdown">
		          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Ballads <span class="caret"></span></a>
		          <ul class="dropdown-menu">
								 <li><%= link_to 'Poems', poems_path %> </li>
								 <li><%= link_to 'Songs', songs_path %> </li>
								 <li><%= link_to 'Add new Ballad', new_place_path %></li>
					
		          </ul>
		        </li>
		        		             <li><%= link_to 'Places', places_path %> </li>

		      </ul>

		      <ul class="nav navbar-nav navbar-right">
		      	           
		        <li class="dropdown">
		          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><strong>Menu </strong><span class="caret"></span></a>
		          <ul class="dropdown-menu">
						<li><%= link_to image_tag("home.png", :style => 'margin-right: 100px;') + 'Home', home_path %></li>		          		           
					    <li><%= link_to image_tag("about.png", :style => 'margin-right: 100px;') + 'About', about_path %></li>
						<li><%= link_to image_tag("contact.png", :style => 'margin-right: 100px;') + 'Contact us', contact_path %></li>
					    <% if end_user_signed_in? %>
								<li><%= link_to image_tag("edit_profile.png", :style => 'margin-right: 100px;') + 'Edit profile', edit_end_user_registration_path %></li>
							<% end %>	
							</li>
						</ul>
					</div>
				</div>
			</nav>
		
			<!-- Hides and shows the 'green menu box' -->
			<!-- Creates transparent menu box over the map -->
			<div class="wrapper">
				<!-- Adds the green box -->
				<div class="background"></div>
				<div class="main">
					<%= yield %>
				</div>
			</div>
			
			<script>
				$(document).ready(function(){
					$(".navbar-brand").click(function(){
						$("div.background, div.main").slideToggle();
					});
				});
			</script>
			
		<!-- Adds map to screen -->
		<div id="map-canvas"></div>
	</body>
</html>